---
abstract: 'An ORLite-based ORM Database API for all CPAN uploads'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  LWP::Online: 1.07
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: ORDB::CPANUploads
name: ORDB-CPANUploads
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DateTime: 0.55
  ORLite::Mirror: 1.20
  Params::Util: 1.00
  perl: 5.8.5
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/ORDB-CPANUploads
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/ORDB-CPANUploads
version: 1.08
